import re

from fastapi.testclient import TestClient
from sqlmodel import Session, select

from app.db import get_setting
from app.models import PushSubscription
from tests.conftest import raw_post, register


def _csrf_token(client) -> str:
    resp = client.get("/settings")
    match = re.search(r'name="csrf_token" value="([^"]+)"', resp.text)
    assert match, "no csrf_token found on /settings"
    return match.group(1)


def test_vapid_public_key_requires_login(client):
    resp = client.get("/push/vapid-public-key", follow_redirects=False)
    assert resp.status_code == 303


def test_vapid_public_key_returns_the_configured_key(client, test_engine):
    register(client, "alice@example.com")
    with Session(test_engine) as session:
        expected = get_setting(session, "vapid_public_key")
    assert expected  # generated by init_db()

    resp = client.get("/push/vapid-public-key")
    assert resp.status_code == 200
    assert resp.json() == {"key": expected}


def test_subscribe_creates_a_push_subscription(client, test_engine):
    register(client, "alice@example.com")
    token = _csrf_token(client)

    resp = raw_post(
        client,
        "/push/subscribe",
        json={"endpoint": "https://push.example/abc", "keys": {"p256dh": "p-key", "auth": "a-key"}},
        headers={"X-CSRF-Token": token},
    )
    assert resp.status_code == 200

    with Session(test_engine) as session:
        subs = session.exec(select(PushSubscription)).all()
        assert len(subs) == 1
        assert subs[0].endpoint == "https://push.example/abc"
        assert subs[0].p256dh == "p-key"
        assert subs[0].auth == "a-key"


def test_subscribe_without_csrf_header_is_rejected(client):
    register(client, "alice@example.com")

    resp = raw_post(
        client,
        "/push/subscribe",
        json={"endpoint": "https://push.example/abc", "keys": {"p256dh": "p-key", "auth": "a-key"}},
    )
    assert resp.status_code == 403


def test_subscribe_rejects_an_incomplete_body(client):
    register(client, "alice@example.com")
    token = _csrf_token(client)

    resp = raw_post(client, "/push/subscribe", json={"endpoint": ""}, headers={"X-CSRF-Token": token})
    assert resp.status_code == 400


def test_resubscribing_the_same_endpoint_updates_ownership_instead_of_duplicating(client, test_engine):
    from app.main import app

    alice = client
    register(alice, "alice@example.com")
    alice_token = _csrf_token(alice)
    raw_post(
        alice,
        "/push/subscribe",
        json={"endpoint": "https://push.example/shared", "keys": {"p256dh": "p1", "auth": "a1"}},
        headers={"X-CSRF-Token": alice_token},
    )

    bob = TestClient(app)
    register(bob, "bob@example.com")
    bob_token = _csrf_token(bob)
    raw_post(
        bob,
        "/push/subscribe",
        json={"endpoint": "https://push.example/shared", "keys": {"p256dh": "p2", "auth": "a2"}},
        headers={"X-CSRF-Token": bob_token},
    )

    with Session(test_engine) as session:
        subs = session.exec(select(PushSubscription)).all()
        assert len(subs) == 1
        assert subs[0].p256dh == "p2"


def test_unsubscribe_deletes_the_callers_own_subscription(client, test_engine):
    register(client, "alice@example.com")
    token = _csrf_token(client)
    raw_post(
        client,
        "/push/subscribe",
        json={"endpoint": "https://push.example/abc", "keys": {"p256dh": "p", "auth": "a"}},
        headers={"X-CSRF-Token": token},
    )

    resp = raw_post(
        client, "/push/unsubscribe", json={"endpoint": "https://push.example/abc"}, headers={"X-CSRF-Token": token}
    )
    assert resp.status_code == 200

    with Session(test_engine) as session:
        assert session.exec(select(PushSubscription)).all() == []


def test_unsubscribe_cannot_delete_another_users_subscription(client, test_engine):
    from app.main import app

    alice = client
    register(alice, "alice@example.com")
    alice_token = _csrf_token(alice)
    raw_post(
        alice,
        "/push/subscribe",
        json={"endpoint": "https://push.example/alice-only", "keys": {"p256dh": "p", "auth": "a"}},
        headers={"X-CSRF-Token": alice_token},
    )

    bob = TestClient(app)
    register(bob, "bob@example.com")
    bob_token = _csrf_token(bob)
    resp = raw_post(
        bob,
        "/push/unsubscribe",
        json={"endpoint": "https://push.example/alice-only"},
        headers={"X-CSRF-Token": bob_token},
    )
    assert resp.status_code == 200  # no-op, not an error - just doesn't delete anything

    with Session(test_engine) as session:
        subs = session.exec(select(PushSubscription)).all()
        assert len(subs) == 1
        assert subs[0].endpoint == "https://push.example/alice-only"


def test_unsubscribe_without_csrf_header_is_rejected(client):
    register(client, "alice@example.com")

    resp = raw_post(client, "/push/unsubscribe", json={"endpoint": "https://push.example/abc"})
    assert resp.status_code == 403
